sudo: false
language: node_js
node_js:
  - "0.12"

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    - USERNAME=martinmicunda
    - PROJECT_NAME=employee-scheduling-ui
    # travis encrypt -r martinmicunda/employee-scheduling-ui GH_TOKEN=<https://help.github.com/articles/creating-an-access-token-for-command-line-use> --add env.global
    - secure: cQyV8hRn1z3yHxuj2ZIGdvS1lRJJEDpNs/cS/4In/QFuq6JR1m/QxZGlJghLqMa/xfdNi0C2u0lpY7AYTPiTByotR8mGfbJHM9wpcFBQuMILclKkta0i9tZDfbog9UQG/ZAGhe+9IR0VsYLTvZTu/8qwH3wywls9sWTn7TDoBl0=

# starts xvfb on display port :99.0 (virtual display for Firefox)
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GITHUB_TOKEN

script:
  - bash -ex ./bin/ci_build.sh

